apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp-project
  labels:
    app: bankapp-w1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bankapp-w1
  template:
    metadata:
      labels:
        app: bankapp-w1
    spec:
      containers:
      - name: bankapp-w1-container
        image: venkt06/bankapp-w1-app
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: bankapp-w1-np-service
  labels:
    app: bankapp-w1
spec:
  selector:
    app: bankapp-w1
  type: NodePort
  ports:
  - nodePort: 31232    
    port: 8081
    
    targetPort: 8081